[package]
name = "diffy-queue-ui"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
diffy-queue = { path = "../diffy-queue" }
eframe = "0.12.0"
egui_web = "0.12.0"
meval = "0.2"

[dependencies.getrandom]
version = "0.2.3"
features = ["js"]
